config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/s/:slug', to: 'links#show', as: :short
  get '/urlaccess', to: 'links#urlaccess'
  root 'links#index'
  resources :links, only: :create
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/link.rb
class Link < ApplicationRecord
  # auto slug generation
  before_validation :generate_slug
  # default_scope -> { order('created_at DESC')}
  
  def generate_slug
    self.slug = SecureRandom.uuid[0..5] if self.slug.nil? || self.slug.empty?
    true
  end
  
  # fast access to the shortened link
  def short
    Rails.application.routes.url_helpers.short_url(slug: self.slug)
  end
  
  # the API
  def self.shorten(url, title = '')   
    link = Link.new(url: url, title: title)
    return link.short if link.save
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  require 'pismo'
  def show
    @link = Link.find_by_slug(params[:slug]) 
    @link.update_attribute(:clicked, @link.clicked + 1)
    redirect_to @link.url
  end

  def index
    @links = Link.all
    @link = Link.new
  end

  def create
    url = params[:link][:url]
    if params[:link][:url].empty?
      flash[:danger] = "Please input url"
    else
      doc = Pismo::Document.new(url)
      flash[:success] = "Sucessfuly Created"
      Link.shorten(url, doc.title)
    end
    redirect_to root_url 
  end

  def urlaccess
    @links = Link.order('clicked desc').limit(100)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <a class="navbar-brand" href="#">URL Shortener</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <%= link_to "Home", root_path, class:"nav-link"%>
                    </li>
                    <li class="nav-item">
                        <%= link_to "Most Access URLs", urlaccess_path, class:"nav-link"%>
                    </li>
                </ul>
        </div>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UrlShortener</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/navbar"%>
    <div class="container">
      <% if flash.any? %>
          <% flash.each do |type, msg| %>
          <div class="mt-4 alert alert-<%= type %>">
              <div><%= msg %></div>
          </div>
          <% end %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/links/index.html.erb
<h1 class="text-center mt-4">All Links</h1> 

<div class="row">
    <div class="col-6 mx-auto mb-4 mt-2">
        <%= form_for @link do |f| %>
            <div class="form-group">
                <%= f.text_field :url, class: "form-control", placeholder: "Link"%>
            </div>
            <%= f.submit "Make link short", class: "btn btn-primary btn-block"%>
        <% end %>
    </div>
</div>

<div class="row">
    <% if @links.length > 0 %>
        <table class="table table-bordered mt-2">
            <tr>
                <th>Title</title>
                <th>Origin Link</th>
                <th>Short Link</th>
                <th>Clicked</th>
            </tr>

            <% @links.each do |link| %>
                <% short_link = "#{request.base_url}/s/#{link.slug}"%>
                <tr>
                    <td><%= link.title%></td>
                    <td><%= link.url %></td>     
                    <td><%= link_to short_link, short_path(link.slug), target: "_blank"%></td>
                    <td><%= link.clicked %></td>
                </tr>
            <% end %>
        </table>
    <% else %>
        <h3> There is no data </h3>
    <% end %>
</div>

app/views/links/show.html.erb
<h1>Links#show</h1>
<p>Find me in app/views/links/show.html.erb</p>

app/views/links/urlaccess.html.erb
<h1 class="text-center mt-4">Top 100 most frequently accessed URLs.</h1> 
<div class="row">
    <% if @links.length > 0 %>
        <table class="table table-bordered mt-2">
            <tr>
                <th>Title</title>
                <th>Origin Link</th>
                <th>Short Link</th>
                <th>Clicked</th>
            </tr>

            <% @links.each do |link| %>
                <% short_link = "#{request.base_url}/s/#{link.slug}"%>
                <tr>
                    <td><%= link.title%></td>
                    <td><%= link.url %></td>     
                    <td><%= link_to short_link, short_path(link.slug), target: "_blank"%></td>
                    <td><%= link.clicked %></td>
                </tr>
            <% end %>
        </table>
    <% else %>
        <h3> There is no data </h3>
    <% end %>
</div>